import func
import re
alfavit = 'абвгдеёэжзиыйклмнопрстуфхцчшщъьюя'
alfavit_with_prob = alfavit + ' '
file = open('text.txt', encoding='utf8')
text = file.read().lower().replace('\n', '')
text = re.sub(r'[^а-яё ]', '', text)
file.close()
temp1 = func.freq_of_letters(text,alfavit_with_prob)
e_temp1 = func.entropiy(temp1, 1)
print(f'Частота букв-{temp1}\nH1={e_temp1}\nНадлишковість - {func.сalc_e(e_temp1, len(alfavit_with_prob))}')
temp11 = func.freq_of_bigrams(text,alfavit_with_prob, True)
e_temp11 = func.entropiy(temp11, 2)
print(f'Частота біграм-{temp11}\nH2={e_temp11}\nНадлишковіть -  {func.сalc_e(e_temp11, len(alfavit_with_prob))}')
temp12 = func.freq_of_bigrams(text,alfavit_with_prob, False)
etemp12 = func.entropiy(temp12, 2)
print(f'Частота перехресних біграм - {temp11}\nH2={etemp12}\nНадлишковість -{func.сalc_e(etemp12, len(alfavit_with_prob))}')
file = open('text.txt', encoding='utf8')
text = file.read().lower().replace('\n', '')
text = re.sub(r'[^а-яё ]', '', text).replace(' ', '')
file.close()
temp2 = func.freq_of_letters(text,alfavit)
e_temp2 = func.entropiy(temp2, 1)
print(f'Частота букв-{temp2}\nH1={e_temp2}\nНадлишковість - {func.сalc_e(e_temp2, len(alfavit))}')
temp21 = func.freq_of_bigrams(text,alfavit, True)
e_temp21 = func.entropiy(temp21, 2)
print(f'Частота біграм-{temp21}\nH2={e_temp21}\nНадлишковість -{func.сalc_e(e_temp21, len(alfavit))}')
temp22 = func.freq_of_bigrams(text, alfavit,False)
etemp22 = func.entropiy(temp22, 2)
print(f'Частота перехресних/біграм - {temp21}\nH2-p = {etemp22}\nНадлилшковість - {func.сalc_e(etemp22, len(alfavit))}')
func.save_results(temp1, temp2, temp11, temp12, temp21, temp22)